# Generated by Django 3.0.4 on 2020-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
