# Generated by Django 3.0.4 on 2020-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
