# Generated by Django 3.0.4 on 2020-04-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribers',
            new_name='subscribtion',
        ),
        migrations.AlterModelOptions(
            name='subscribtion',
            options={'verbose_name_plural': 'subscribtions'},
        ),
    ]
