# Generated by Django 3.0.4 on 2020-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200321_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_on_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
