# Generated by Django 3.0.4 on 2020-04-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
