# Generated by Django 3.0.4 on 2020-04-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200415_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name_plural': 'Chefs'},
        ),
    ]
