# Generated by Django 3.0.4 on 2020-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20200422_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(to='blogging.Comment'),
        ),
    ]
