# Generated by Django 3.0.4 on 2020-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_auto_20200504_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text1_bs',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text2_bs',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text3_bs',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_person_bs',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
