# Generated by Django 3.0.4 on 2020-05-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0011_auto_20200504_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text3_bs',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
